/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import conexion.Conectar;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.event.KeyEvent;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author argue
 */
public class Login extends javax.swing.JFrame {

    int coor_x;
    int coor_y;    
    
    PreparedStatement ps;
    ResultSet rs;
    
    static String user="";

    public String getUser() {
        return user;
    }
    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setBackground(new Color(0, 0, 0, 1));
        
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelLogo = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jButtonLoginRegistro = new javax.swing.JButton();
        jButtonLoginSalir = new javax.swing.JButton();
        jLabelAcercade = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(139, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(139, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 1500));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 600, 20));

        jSeparator2.setBackground(new java.awt.Color(139, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(139, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 1500));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 600, 20));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4/imagenes/cocheee (1).png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 230, 100));

        jLabelInicio.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabelInicio.setForeground(new java.awt.Color(189, 0, 0));
        jLabelInicio.setText("INICIAR SESIÓN");
        getContentPane().add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jLabelContraseña.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Contraseña");
        getContentPane().add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre de usuario");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jTextFieldUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.setForeground(new java.awt.Color(139, 0, 0));
        jTextFieldUsuario.setText("Inserte usuario");
        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusLost(evt);
            }
        });
        jTextFieldUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 450, -1));

        jPasswordFieldContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldContraseña.setForeground(new java.awt.Color(139, 0, 0));
        jPasswordFieldContraseña.setText("jPasswordField1");
        jPasswordFieldContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseñaFocusLost(evt);
            }
        });
        jPasswordFieldContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordFieldContraseñaMouseClicked(evt);
            }
        });
        jPasswordFieldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldContraseñaActionPerformed(evt);
            }
        });
        jPasswordFieldContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldContraseñaKeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 450, -1));

        jButtonLogin.setBackground(new java.awt.Color(139, 0, 0));
        jButtonLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseExited(evt);
            }
        });
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jButtonLoginRegistro.setBackground(new java.awt.Color(139, 0, 0));
        jButtonLoginRegistro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonLoginRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLoginRegistro.setText("Registro");
        jButtonLoginRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLoginRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoginRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoginRegistroMouseExited(evt);
            }
        });
        jButtonLoginRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoginRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jButtonLoginSalir.setBackground(new java.awt.Color(139, 0, 0));
        jButtonLoginSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonLoginSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLoginSalir.setText("Salir");
        jButtonLoginSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLoginSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoginSalirMouseExited(evt);
            }
        });
        jButtonLoginSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoginSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        jLabelAcercade.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelAcercade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAcercade.setText("Acerca de");
        jLabelAcercade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAcercade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAcercadeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAcercadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAcercadeMouseExited(evt);
            }
        });
        getContentPane().add(jLabelAcercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, -1, -1));

        jLabelSalir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelSalir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalir.setText("X");
        jLabelSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseExited(evt);
            }
        });
        getContentPane().add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 1));
        jPanel1.setForeground(new java.awt.Color(0, 0, 1));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 510));

        jLabelImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4/imagenes/portada.png"))); // NOI18N
        getContentPane().add(jLabelImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginSalirActionPerformed
        // TODO add your handling code here:
        int ventana = JOptionPane.showConfirmDialog(null, "Seguro que quieres salir", "Salir", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

        switch (ventana) {
            case 0:
                System.out.println("Has pulsado Yes");
                dispose();
                System.exit(0);
                break;
            case 1:
                System.out.println("Has pulsado No");
                break;
            case 2:
                System.out.println("Has pulsado Cancel");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jButtonLoginSalirActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        String password = String.valueOf(jPasswordFieldContraseña.getText());

        if (jTextFieldUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debes de introducir un nombre de usuario", "Usuario", 0);
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(null, "Debes de introducir una contraseña", "Error de contraeña", 0);
        }else if (datosAcceso()==true) {
            dispose();
            Principal principal=new Principal();
            principal.setVisible(true);
            
            
        } else {
            JOptionPane.showMessageDialog(this, "Contraseña y usuario incorrecto", "Login correcto", 0);
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private boolean datosAcceso() {
        boolean exito=false;
        Conectar con = new Conectar();
        Connection conexion = con.getConexion();
        try {
            //ps = conexion.prepareStatement("SELECT usuario, password FROM registro WHERE usuario=? AND password = ?");
            ps = conexion.prepareStatement("SELECT usuario, password FROM registro");
            //ps.setString(1, usuario.getText());
            //ps.setString(2, pass.getText());

            rs = ps.executeQuery();
            while ( rs.next() ){
                if(jTextFieldUsuario.getText().equals(rs.getString("usuario")) && jPasswordFieldContraseña.getText().equals(rs.getString("password"))){
                    user=jTextFieldUsuario.getText();
                    exito=true;
                    break;
                }
            }
            if (!exito) {
                JOptionPane.showMessageDialog(this, "Las credenciales de acceso no son correctas.", "Error login", 0);
                jTextFieldUsuario.setText("Ingrese su nombre");
                jPasswordFieldContraseña.setText("Ingrese la contraseña");
            }
            rs.close();
            ps.close();
            conexion.close();

        } catch (Exception e) {
            System.err.print(e);
        }
        return exito;
    }
    
    private void jPasswordFieldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaActionPerformed
        // TODO add your handling code here:      
    }//GEN-LAST:event_jPasswordFieldContraseñaActionPerformed

    private void jButtonLoginRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginRegistroActionPerformed
        // TODO add your handling code here:
        dispose();
        Registro registro = new Registro();
        registro.setVisible(true);


    }//GEN-LAST:event_jButtonLoginRegistroActionPerformed

    private void jLabelAcercadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAcercadeMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Información sobre nosotros");
    }//GEN-LAST:event_jLabelAcercadeMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        coor_x = evt.getX();
        coor_y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - coor_x, y - coor_y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseExited
        // TODO add your handling code here:
        jLabelSalir.setForeground(Color.white);
        jLabelSalir.setBackground(new Color(0, 0, 0, 1));
    }//GEN-LAST:event_jLabelSalirMouseExited

    private void jLabelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseEntered
        // TODO add your handling code here:
        jLabelSalir.setBackground(new Color(0, 0, 0, 1));
        jLabelSalir.setForeground(new Color(139, 0, 0));
    }//GEN-LAST:event_jLabelSalirMouseEntered

    private void jLabelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseClicked
        // TODO add your handling code here:
        jLabelSalir.setBackground(new Color(0, 0, 0, 1));

        String motivo = JOptionPane.showInputDialog(null, "Por favor indicanos el motivo");

        if (motivo != null) {
            if (motivo.equals("")) {
                JOptionPane.showMessageDialog(null, "Así no esta te la guardo ", "Descripcion", 2);
            } else {
                JOptionPane.showMessageDialog(null, "Entiendo tu motivos", "Descripcion", 1);
            }
            dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_jLabelSalirMouseClicked

    private void jTextFieldUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioMouseClicked
        // TODO add your handling code here:
        jTextFieldUsuario.setText("");
    }//GEN-LAST:event_jTextFieldUsuarioMouseClicked

    private void jPasswordFieldContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaMouseClicked
        // TODO add your handling code here:
        jPasswordFieldContraseña.setText("");
    }//GEN-LAST:event_jPasswordFieldContraseñaMouseClicked

    private void jButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoginMouseClicked

    private void jButtonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseEntered
        // TODO add your handling code here:
        jButtonLogin.setBackground(Color.white);
        jButtonLogin.setForeground(new Color(139, 0, 0));
    }//GEN-LAST:event_jButtonLoginMouseEntered

    private void jButtonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseExited
        // TODO add your handling code here:
        jButtonLogin.setBackground(new Color(139, 0, 0));
        jButtonLogin.setForeground(Color.white);
    }//GEN-LAST:event_jButtonLoginMouseExited

    private void jButtonLoginRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginRegistroMouseEntered
        // TODO add your handling code here:
        jButtonLoginRegistro.setBackground(Color.white);
        jButtonLoginRegistro.setForeground(new Color(139, 0, 0));
    }//GEN-LAST:event_jButtonLoginRegistroMouseEntered

    private void jButtonLoginRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginRegistroMouseExited
        // TODO add your handling code here:
        jButtonLoginRegistro.setBackground(new Color(139, 0, 0));
        jButtonLoginRegistro.setForeground(Color.white);
    }//GEN-LAST:event_jButtonLoginRegistroMouseExited

    private void jButtonLoginSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginSalirMouseEntered
        // TODO add your handling code here:
        jButtonLoginSalir.setBackground(Color.white);
        jButtonLoginSalir.setForeground(new Color(139, 0, 0));
    }//GEN-LAST:event_jButtonLoginSalirMouseEntered

    private void jButtonLoginSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginSalirMouseExited
        // TODO add your handling code here:
        jButtonLoginSalir.setBackground(new Color(139, 0, 0));
        jButtonLoginSalir.setForeground(Color.white);
    }//GEN-LAST:event_jButtonLoginSalirMouseExited

    private void jLabelAcercadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAcercadeMouseEntered
        // TODO add your handling code here:
        jLabelAcercade.setBackground(Color.white);
        jLabelAcercade.setForeground(new Color(139, 0, 0));
    }//GEN-LAST:event_jLabelAcercadeMouseEntered

    private void jLabelAcercadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAcercadeMouseExited
        // TODO add your handling code here:
        jLabelAcercade.setBackground(new Color(139, 0, 0));
        jLabelAcercade.setForeground(Color.white);
    }//GEN-LAST:event_jLabelAcercadeMouseExited

    private void jButtonLoginRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginRegistroMouseClicked
        // TODO add your handling code here:
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButtonLoginRegistroMouseClicked

    private void jTextFieldUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusGained
        // TODO add your handling code here:
        if(jTextFieldUsuario.getText().equals("Inserte usuario") || jTextFieldUsuario.getText().equals("")) {
            jTextFieldUsuario.setText("");
        }
        
    }//GEN-LAST:event_jTextFieldUsuarioFocusGained

    private void jPasswordFieldContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaFocusGained
        // TODO add your handling code here:
            jPasswordFieldContraseña.setText("");
        
    }//GEN-LAST:event_jPasswordFieldContraseñaFocusGained

    private void jTextFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusLost
        // TODO add your handling code here:
        if("".equals(jTextFieldUsuario.getText())){
            jTextFieldUsuario.setText("Inserte usuario");
        }
    }//GEN-LAST:event_jTextFieldUsuarioFocusLost

    private void jPasswordFieldContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaFocusLost
        // TODO add your handling code here:
        if("".equals(jPasswordFieldContraseña.getText())){
            jPasswordFieldContraseña.setText("jPasswordField1");
        }
    }//GEN-LAST:event_jPasswordFieldContraseñaFocusLost

    private void jPasswordFieldContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaKeyPressed
        // TODO add your handling code here:
        
        String password = String.valueOf(jPasswordFieldContraseña.getText());
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {

        if (jTextFieldUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debes de introducir un nombre de usuario", "Usuario", 0);
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(null, "Debes de introducir una contraseña", "Error de contraeña", 0);
        }else if (datosAcceso()==true) {
            dispose();
            Principal principal=new Principal();
            principal.setVisible(true); 
        } else {
            JOptionPane.showMessageDialog(this, "Contraseña y usuario incorrecto", "Login correcto", 0);
        }
        }
        
    }//GEN-LAST:event_jPasswordFieldContraseñaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLoginRegistro;
    private javax.swing.JButton jButtonLoginSalir;
    private javax.swing.JLabel jLabelAcercade;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelImagenFondo;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
