/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import conexion.Conectar;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Icon;

/**
 *
 * @author argue
 */
public class Principal extends javax.swing.JFrame {

    int coor_x;
    int coor_y;
    
    PreparedStatement ps;
    ResultSet rs;   

    /**
     * Creates new form NewJFrame
     */
    public Principal() {
        
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setBackground(new Color(0,0,0,1));
        
        
        //jLabelCesta.setOpaque(true);
//        jLabelClientes.setOpaque(true);
//        jLabelProovedores.setOpaque(true);
//        jLabelStock.setOpaque(true);
//        jLabelPedidos.setOpaque(true);
//        jLabelGestion.setOpaque(true);
        Login login=new Login();
        jLabelUusuario.setText("Usuario conectado: "+login.getUser());

    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelUusuario = new javax.swing.JLabel();
        jLabelGestion = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();
        jLabelCesta = new javax.swing.JLabel();
        jLabelPedidos = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        jLabelProovedores = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4/imagenes/cocheee.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 70));

        jLabelSalir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelSalir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalir.setText("X");
        jLabelSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseExited(evt);
            }
        });
        getContentPane().add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 1));
        jPanel1.setForeground(new java.awt.Color(0, 0, 1));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabelUusuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelUusuario.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(456, Short.MAX_VALUE)
                .addComponent(jLabelUusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 30));

        jLabelGestion.setBackground(new java.awt.Color(255, 255, 255));
        jLabelGestion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ms-icon-144x144_11.png"))); // NOI18N
        jLabelGestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelGestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelGestionMouseExited(evt);
            }
        });
        getContentPane().add(jLabelGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 150, 140));

        jLabelStock.setBackground(new java.awt.Color(255, 255, 255));
        jLabelStock.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ms-icon-144x144_14.png"))); // NOI18N
        jLabelStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelStockMouseExited(evt);
            }
        });
        getContentPane().add(jLabelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 150, 140));

        jLabelCesta.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCesta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ms-icon-144x144_6.png"))); // NOI18N
        jLabelCesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCestaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCestaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCestaMouseExited(evt);
            }
        });
        getContentPane().add(jLabelCesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 150, 140));

        jLabelPedidos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPedidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ms-icon-144x144_15.png"))); // NOI18N
        jLabelPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPedidosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPedidosMouseExited(evt);
            }
        });
        getContentPane().add(jLabelPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 150, 140));

        jLabelClientes.setBackground(new java.awt.Color(255, 255, 255));
        jLabelClientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ms-icon-144x144_12.png"))); // NOI18N
        jLabelClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClientesMouseExited(evt);
            }
        });
        getContentPane().add(jLabelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 150, 140));

        jLabelProovedores.setBackground(new java.awt.Color(255, 255, 255));
        jLabelProovedores.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProovedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ms-icon-144x144_13.png"))); // NOI18N
        jLabelProovedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProovedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProovedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelProovedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelProovedoresMouseExited(evt);
            }
        });
        getContentPane().add(jLabelProovedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 150, 140));

        jLabelInicio.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabelInicio.setForeground(new java.awt.Color(189, 0, 0));
        jLabelInicio.setText("PANEL PRINCIPAL");
        getContentPane().add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(139, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(139, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 1500));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 700, 40));

        jLabelImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4/imagenes/portada.png"))); // NOI18N
        getContentPane().add(jLabelImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        coor_x = evt.getX();
        coor_y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - coor_x, y - coor_y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseClicked
        // TODO add your handling code here:
        jLabelSalir.setBackground(new Color(0, 0, 0, 1));
            dispose();
            Login login=new Login();
            login.setVisible(true);
        
    }//GEN-LAST:event_jLabelSalirMouseClicked

    private void jLabelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseEntered
        // TODO add your handling code here:
        jLabelSalir.setBackground(new Color(0, 0, 0, 1));
        jLabelSalir.setForeground(new Color(139, 0, 0));
    }//GEN-LAST:event_jLabelSalirMouseEntered

    private void jLabelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseExited
        // TODO add your handling code here:
        jLabelSalir.setForeground(Color.white);
        jLabelSalir.setBackground(new Color(0, 0, 0, 1));
    }//GEN-LAST:event_jLabelSalirMouseExited

    private void jLabelCestaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCestaMouseEntered
        // TODO add your handling code here:
        jLabelCesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/favicon-96x96_6.png")));
        jLabelCesta.setHorizontalAlignment((int) CENTER_ALIGNMENT);
    }//GEN-LAST:event_jLabelCestaMouseEntered

    private void jLabelCestaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCestaMouseExited
        // TODO add your handling code here:
        jLabelCesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ms-icon-144x144_6.png")));
    }//GEN-LAST:event_jLabelCestaMouseExited

    private void jLabelClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientesMouseEntered
        // TODO add your handling code here:
        jLabelClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/favicon-96x96_12.png")));
        jLabelClientes.setHorizontalAlignment((int) CENTER_ALIGNMENT);
    }//GEN-LAST:event_jLabelClientesMouseEntered

    private void jLabelClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientesMouseExited
        // TODO add your handling code here:
        jLabelClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ms-icon-144x144_12.png")));
    }//GEN-LAST:event_jLabelClientesMouseExited

    private void jLabelGestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGestionMouseEntered
        // TODO add your handling code here:
        jLabelGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/favicon-96x96_11.png")));
        jLabelGestion.setHorizontalAlignment((int) CENTER_ALIGNMENT);
    }//GEN-LAST:event_jLabelGestionMouseEntered

    private void jLabelGestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGestionMouseExited
        // TODO add your handling code here:
        jLabelGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ms-icon-144x144_11.png")));
    }//GEN-LAST:event_jLabelGestionMouseExited

    private void jLabelStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStockMouseEntered
        // TODO add your handling code here:
        jLabelStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/favicon-96x96_14.png")));
        jLabelStock.setHorizontalAlignment((int) CENTER_ALIGNMENT);
    }//GEN-LAST:event_jLabelStockMouseEntered

    private void jLabelStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStockMouseExited
        // TODO add your handling code here:
         jLabelStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ms-icon-144x144_14.png")));
    }//GEN-LAST:event_jLabelStockMouseExited

    private void jLabelPedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPedidosMouseEntered
        // TODO add your handling code here:
        jLabelPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/favicon-96x96_15.png")));
        jLabelPedidos.setHorizontalAlignment((int) CENTER_ALIGNMENT);
    }//GEN-LAST:event_jLabelPedidosMouseEntered

    private void jLabelPedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPedidosMouseExited
        // TODO add your handling code here:
        jLabelPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ms-icon-144x144_15.png")));
    }//GEN-LAST:event_jLabelPedidosMouseExited

    private void jLabelCestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCestaMouseClicked
        // TODO add your handling code here:
        dispose();
        
        NPedidos npe=new NPedidos();
        npe.setVisible(true);
    }//GEN-LAST:event_jLabelCestaMouseClicked

    private void jLabelClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientesMouseClicked
        // TODO add your handling code here:
        dispose();
        Clientes clientes=new Clientes();
        clientes.setVisible(true);
    }//GEN-LAST:event_jLabelClientesMouseClicked

    private void jLabelStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStockMouseClicked
        // TODO add your handling code here:
        dispose();
        Stock stock=new Stock();
        stock.setVisible(true);
    }//GEN-LAST:event_jLabelStockMouseClicked

    private void jLabelPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPedidosMouseClicked
        // TODO add your handling code here:
        dispose();
        LPedidos lpe=new LPedidos();
        lpe.setVisible(true);
    }//GEN-LAST:event_jLabelPedidosMouseClicked

    private void jLabelGestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGestionMouseClicked
        // TODO add your handling code here:
        dispose();
        Gestion ges=new Gestion();
        ges.setVisible(true);
    }//GEN-LAST:event_jLabelGestionMouseClicked

    private void jLabelProovedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProovedoresMouseExited
        // TODO add your handling code here:
        jLabelProovedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ms-icon-144x144_13.png")));
    }//GEN-LAST:event_jLabelProovedoresMouseExited

    private void jLabelProovedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProovedoresMouseEntered
        // TODO add your handling code here:
        jLabelProovedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/favicon-96x96_13.png")));
        jLabelProovedores.setHorizontalAlignment((int) CENTER_ALIGNMENT);
    }//GEN-LAST:event_jLabelProovedoresMouseEntered

    private void jLabelProovedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProovedoresMouseClicked
        // TODO add your handling code here:
        dispose();
        Proveedores pro=new Proveedores();
        pro.setVisible(true);

    }//GEN-LAST:event_jLabelProovedoresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCesta;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelGestion;
    private javax.swing.JLabel jLabelImagenFondo;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelPedidos;
    private javax.swing.JLabel jLabelProovedores;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jLabelUusuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
