/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import conexion.Conectar;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author argue
 */
public class Registro extends javax.swing.JFrame {

    int coor_x;
    int coor_y;
    
    PreparedStatement ps;
    ResultSet rs;

    /**
     * Creates new form NewJFrame
     */
    public Registro() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setBackground(new Color(0,0,0,1));
        jCheckBoxTerminos.setBackground(new Color(0,0,0,1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabelLogo = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelContraseña1 = new javax.swing.JLabel();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonLoginRegistro = new javax.swing.JButton();
        jButtonLoginSalir = new javax.swing.JButton();
        jPasswordFieldContraseña1 = new javax.swing.JPasswordField();
        jLabelNombre = new javax.swing.JLabel();
        jCheckBoxTerminos = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabelImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(139, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(139, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 1500));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 600, 20));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4/imagenes/cocheee (1).png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 230, 100));

        jLabelInicio.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabelInicio.setForeground(new java.awt.Color(189, 0, 0));
        jLabelInicio.setText("REGISTRO");
        getContentPane().add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jTextFieldUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.setForeground(new java.awt.Color(139, 0, 0));
        jTextFieldUsuario.setText("Inserte usuario");
        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusLost(evt);
            }
        });
        jTextFieldUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUsuarioMouseClicked(evt);
            }
        });
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 450, -1));

        jLabelContraseña.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Contraseña");
        getContentPane().add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabelContraseña1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelContraseña1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña1.setText("Repite Contraseña");
        getContentPane().add(jLabelContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jPasswordFieldContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldContraseña.setForeground(new java.awt.Color(139, 0, 0));
        jPasswordFieldContraseña.setText("jPasswordField1");
        jPasswordFieldContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseñaFocusLost(evt);
            }
        });
        jPasswordFieldContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordFieldContraseñaMouseClicked(evt);
            }
        });
        jPasswordFieldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 450, -1));

        jSeparator1.setBackground(new java.awt.Color(139, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(139, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 1500));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 600, 20));

        jButtonLoginRegistro.setBackground(new java.awt.Color(139, 0, 0));
        jButtonLoginRegistro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonLoginRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLoginRegistro.setText("Registrar");
        jButtonLoginRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLoginRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoginRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoginRegistroMouseExited(evt);
            }
        });
        jButtonLoginRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoginRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jButtonLoginSalir.setBackground(new java.awt.Color(139, 0, 0));
        jButtonLoginSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonLoginSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLoginSalir.setText("Volver a Login");
        jButtonLoginSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLoginSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoginSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoginSalirMouseExited(evt);
            }
        });
        jButtonLoginSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoginSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));

        jPasswordFieldContraseña1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldContraseña1.setForeground(new java.awt.Color(139, 0, 0));
        jPasswordFieldContraseña1.setText("jPasswordField1");
        jPasswordFieldContraseña1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseña1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseña1FocusLost(evt);
            }
        });
        jPasswordFieldContraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordFieldContraseña1MouseClicked(evt);
            }
        });
        jPasswordFieldContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldContraseña1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 450, -1));

        jLabelNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre de usuario");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jCheckBoxTerminos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBoxTerminos.setForeground(new java.awt.Color(189, 0, 0));
        jCheckBoxTerminos.setText("Aceptar términos y condiciones.");
        getContentPane().add(jCheckBoxTerminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 310, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 1));
        jPanel1.setForeground(new java.awt.Color(0, 0, 1));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 30));

        jLabelImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4/imagenes/portada.png"))); // NOI18N
        getContentPane().add(jLabelImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login login=new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButtonLoginSalirActionPerformed

    private void jPasswordFieldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaActionPerformed
        // TODO add your handling code here:      
    }//GEN-LAST:event_jPasswordFieldContraseñaActionPerformed

    private void jButtonLoginRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginRegistroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonLoginRegistroActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        coor_x = evt.getX();
        coor_y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - coor_x, y - coor_y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jTextFieldUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioMouseClicked
        // TODO add your handling code here:
        jTextFieldUsuario.setText("");
    }//GEN-LAST:event_jTextFieldUsuarioMouseClicked

    private void jPasswordFieldContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaMouseClicked
        // TODO add your handling code here:
        jPasswordFieldContraseña.setText("");
    }//GEN-LAST:event_jPasswordFieldContraseñaMouseClicked

    private void jButtonLoginRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginRegistroMouseEntered
        // TODO add your handling code here:
        jButtonLoginRegistro.setBackground(Color.white);
        jButtonLoginRegistro.setForeground(new Color(139,0,0));
    }//GEN-LAST:event_jButtonLoginRegistroMouseEntered

    private void jButtonLoginRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginRegistroMouseExited
        // TODO add your handling code here:
        jButtonLoginRegistro.setBackground(new Color(139,0,0));
        jButtonLoginRegistro.setForeground(Color.white);
    }//GEN-LAST:event_jButtonLoginRegistroMouseExited

    private void jButtonLoginSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginSalirMouseEntered
        // TODO add your handling code here:
        jButtonLoginSalir.setBackground(Color.white);
        jButtonLoginSalir.setForeground(new Color(139,0,0));
    }//GEN-LAST:event_jButtonLoginSalirMouseEntered

    private void jButtonLoginSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginSalirMouseExited
        // TODO add your handling code here:
        jButtonLoginSalir.setBackground(new Color(139,0,0));
        jButtonLoginSalir.setForeground(Color.white);
    }//GEN-LAST:event_jButtonLoginSalirMouseExited

    private void jPasswordFieldContraseña1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseña1MouseClicked
        // TODO add your handling code here:
        jPasswordFieldContraseña1.setText("");
    }//GEN-LAST:event_jPasswordFieldContraseña1MouseClicked

    private void jPasswordFieldContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldContraseña1ActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonLoginRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginRegistroMouseClicked
        // TODO add your handling code here:
        String password = String.valueOf(jPasswordFieldContraseña.getText());
        String passwordrepite = String.valueOf(jPasswordFieldContraseña1.getText());
        
        if(jCheckBoxTerminos.isSelected()){
        
        if ((jTextFieldUsuario.getText()).equals("") || jTextFieldUsuario.getText().equals("Inserte usuario")) {
            JOptionPane.showMessageDialog(this, "Debes introducir un usuario correcto", "Error login", 0);
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(this, "Debes introducir contraseña", "Error login", 0);
        } else if (passwordrepite.equals("")) {
            JOptionPane.showMessageDialog(this, "Debes introducir contraseña", "Error login", 0);
        } else if (password.equals(passwordrepite)) {
            
            registrarUsuraio();
        } else {
            JOptionPane.showMessageDialog(this, "Las contraseña no coincide", "Login correcto", 0);
            jPasswordFieldContraseña1.setText("");
            jPasswordFieldContraseña.setText("");
            jTextFieldUsuario.setText("");
        }
        }else{
            JOptionPane.showMessageDialog(this, "Debes aceptar términos y condiciones", "Error login", 0);
        }
    }//GEN-LAST:event_jButtonLoginRegistroMouseClicked

    public void registrarUsuraio() {

        Conectar con = new Conectar();
        Connection conexion = con.getConexion();
        try {
            ps = conexion.prepareStatement("INSERT INTO registro(usuario,password) VALUES (?,?)");
            ps.setString(1, jTextFieldUsuario.getText());
            ps.setString(2, jPasswordFieldContraseña.getText());

            int res = ps.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(this, "El usuario se ha creado correctamente.", "Registro usuario", 1);
                this.dispose();
                Login login = new Login();
                login.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar el usuario en BBDD.", "Registro usuario", 0);
                jTextFieldUsuario.setText("Ingrese su nombre");
                jPasswordFieldContraseña.setText("Ingrese la contraseña");
                jPasswordFieldContraseña.setText("Ingrese la contraseña");
            }

            conexion.close();

        } catch (Exception e) {
            System.err.print(e);
        }
    }
    
    private void jButtonLoginSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Login login=new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButtonLoginSalirMouseClicked

    private void jTextFieldUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusGained
        // TODO add your handling code here:
        if(jTextFieldUsuario.getText().equals("Inserte usuario") || jTextFieldUsuario.getText().equals("")) {
            jTextFieldUsuario.setText("");
        }
    }//GEN-LAST:event_jTextFieldUsuarioFocusGained

    private void jTextFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusLost
        // TODO add your handling code here:
        if("".equals(jTextFieldUsuario.getText())){
            jTextFieldUsuario.setText("Inserte usuario");
        }
    }//GEN-LAST:event_jTextFieldUsuarioFocusLost

    private void jPasswordFieldContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaFocusGained
        // TODO add your handling code here:
        jPasswordFieldContraseña.setText("");
    }//GEN-LAST:event_jPasswordFieldContraseñaFocusGained

    private void jPasswordFieldContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaFocusLost
        // TODO add your handling code here:
        if("".equals(jPasswordFieldContraseña.getText())){
            jPasswordFieldContraseña.setText("jPasswordField1");
        }
    }//GEN-LAST:event_jPasswordFieldContraseñaFocusLost

    private void jPasswordFieldContraseña1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseña1FocusGained
        // TODO add your handling code here:
        jPasswordFieldContraseña1.setText("");
    }//GEN-LAST:event_jPasswordFieldContraseña1FocusGained

    private void jPasswordFieldContraseña1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseña1FocusLost
        // TODO add your handling code here:
        if("".equals(jPasswordFieldContraseña1.getText())){
            jPasswordFieldContraseña1.setText("jPasswordField1");
        }
    }//GEN-LAST:event_jPasswordFieldContraseña1FocusLost

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoginRegistro;
    private javax.swing.JButton jButtonLoginSalir;
    private javax.swing.JCheckBox jCheckBoxTerminos;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelContraseña1;
    private javax.swing.JLabel jLabelImagenFondo;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JPasswordField jPasswordFieldContraseña1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
